import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';

// Vercel's file tracer resolves physical .js files. It does not consistently
// discover .tsx dependencies through a .js specifier. Emit the dependency tree
// next to its sources before Vercel packages the Node function. Never emit a
// second api/anfrage.js entrypoint (that would duplicate the public route).
const root = process.cwd();
const output = path.join(root, '.cache', 'email-build');
const program = ts.createProgram(['api/anfrage.ts'], {
  target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.NodeNext,
  moduleResolution: ts.ModuleResolutionKind.NodeNext, jsx: ts.JsxEmit.ReactJSX,
  esModuleInterop: true, skipLibCheck: true, strict: true,
  rootDir: root, outDir: output,
});
const diagnostics = ts.getPreEmitDiagnostics(program);
if (diagnostics.some((d) => d.category === ts.DiagnosticCategory.Error)) {
  console.error(ts.formatDiagnosticsWithColorAndContext(diagnostics, {
    getCanonicalFileName: (f) => f, getCurrentDirectory: () => root, getNewLine: () => '\n',
  }));
  process.exit(1);
}
const files = [];
program.emit(undefined, (filename, text) => {
  const relative = path.relative(output, filename).replaceAll('\\', '/');
  if (relative.startsWith('api/') || relative === 'types.js') return;
  if (!/^(data|emails)\/[^/]+\.js$/.test(relative)) throw new Error(`Unexpected email dependency: ${relative}`);
  fs.writeFileSync(path.join(root, relative), `// Generated by scripts/build-email.mjs; edit the TypeScript source.\n${text}`);
  files.push(relative);
});
console.log(`[build-email] ${files.length} server dependency files emitted: ${files.join(', ')}`);
